title: OKim's Razor
description: Exploring the least likely
author: Kim Duffy
github: https://github.com/kimdhamilton
about: Blockchain, Self-sovereign identity
#disqus_shortname: stackproblems
#google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/me_lil.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  medium_posts:

social:
    - icon: fa-twitter
      link: "https://twitter.com/kimdhamilton"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/kimdhamilton/"
    - icon: fa-github
      link: "https://github.com/kimdhamilton"

share:
  twitter_username: kimdhamilton

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Talks
      url: /talks/
    - text: XML Feed
      url: /feed.xml

url: "https://kimdhamilton.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
